name: fix code styling

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  lint:
    uses: ugarit/.github/.github/workflows/coding-standards.yml@9c15e86fffce728fb6c50ebeae24fd63e98f4d1d # main
    with:
      php: "8.3"
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies
        run: npm install

      - name: Format code
        run: npm run format

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "Fix code style"
